// Ticket ID generators with mode-specific prefixes
// Format: PREFIX-XXXX-XXXX (e.g., BUS-A4F2-9X1Q)

const ALPHABET = '23456789ABCDEFGHJKLMNPQRSTUVWXYZ'; // no 0/O/1/I

function randomChunk(len = 4): string {
  let out = '';
  for (let i = 0; i < len; i++) {
    out += ALPHABET[Math.floor(Math.random() * ALPHABET.length)];
  }
  return out;
}

export function generateTicketId(prefix: string): string {
  return `${prefix}-${randomChunk(4)}-${randomChunk(4)}`;
}

export function busTicketId(): string  { return generateTicketId('BUS'); }
export function railTicketId(): string { return generateTicketId('EDR'); }
export function eventTicketId(): string { return generateTicketId('EVT'); }

// In production this would be an Ed25519-signed JWT-like token
// generated by the backend. For now we return a deterministic placeholder.
export function buildQrPayload(ticketId: string): string {
  // Real impl: { tid, exp, sig } base64-encoded, signed with edge key
  const stub = btoa(JSON.stringify({
    tid: ticketId,
    iat: Date.now(),
    exp: Date.now() + 86_400_000,
    v: 1,
  }));
  return `tikt://${stub}`;
}

// Decode for the scanner side (for the locked/active demo logic)
export function decodeQrPayload(payload: string): { tid: string; exp: number } | null {
  try {
    if (!payload.startsWith('tikt://')) return null;
    const json = JSON.parse(atob(payload.slice(7)));
    return { tid: json.tid, exp: json.exp };
  } catch { return null; }
}
